name: Test install on Python 3.10

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "test_release" branch
  push:
    branches: [ "test_release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-310:
    name: Build and publish python distributions to TestPyPI
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests