name: Test Installs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "test_release" branch
  push:
    branches: [ "test_release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency: release
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-39-ubuntu:
    name: Build on Python 3.9 ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-39-mac:
    name: Build on Python 3.9 mac
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-39-windows:
    name: Build on Python 3.9 windows
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-310-ubuntu:
    name: Build on Python 3.10 ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-310-mac:
    name: Build on Python 3.10 mac
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-310-windows:
    name: Build on Python 3.10 windows
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-311-ubuntu:
    name: Build on Python 3.11 ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-311-mac:
    name: Build on Python 3.11 mac
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-311-windows:
    name: Build on Python 3.11 windows
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-312-ubuntu:
    name: Build on Python 3.12 ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-312-mac:
    name: Build on Python 3.12 mac
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
  build-312-windows:
    name: Build on Python 3.12 windows
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: 'test_release'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install teaspoon for testing
        run: pip install .
      - name: Run tests
        run: make tests
        